/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as ComposerRouteImport } from './routes/composer'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as MemoriesIdRouteImport } from './routes/memories.$id'
import { Route as ComposerDevModesIdRouteImport } from './routes/composer.dev-modes.$id'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposerRoute = ComposerRouteImport.update({
  id: '/composer',
  path: '/composer',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const MemoriesIdRoute = MemoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MemoriesRoute,
} as any)
const ComposerDevModesIdRoute = ComposerDevModesIdRouteImport.update({
  id: '/dev-modes/$id',
  path: '/dev-modes/$id',
  getParentRoute: () => ComposerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRoute
  '/composer': typeof ComposerRouteWithChildren
  '/memories': typeof MemoriesRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/memories/$id': typeof MemoriesIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/composer/dev-modes/$id': typeof ComposerDevModesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRoute
  '/composer': typeof ComposerRouteWithChildren
  '/memories': typeof MemoriesRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/memories/$id': typeof MemoriesIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/composer/dev-modes/$id': typeof ComposerDevModesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRoute
  '/composer': typeof ComposerRouteWithChildren
  '/memories': typeof MemoriesRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/memories/$id': typeof MemoriesIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/composer/dev-modes/$id': typeof ComposerDevModesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/canvas'
    | '/composer'
    | '/memories'
    | '/projects'
    | '/memories/$id'
    | '/projects/$id'
    | '/composer/dev-modes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/canvas'
    | '/composer'
    | '/memories'
    | '/projects'
    | '/memories/$id'
    | '/projects/$id'
    | '/composer/dev-modes/$id'
  id:
    | '__root__'
    | '/'
    | '/canvas'
    | '/composer'
    | '/memories'
    | '/projects'
    | '/memories/$id'
    | '/projects/$id'
    | '/composer/dev-modes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanvasRoute: typeof CanvasRoute
  ComposerRoute: typeof ComposerRouteWithChildren
  MemoriesRoute: typeof MemoriesRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composer': {
      id: '/composer'
      path: '/composer'
      fullPath: '/composer'
      preLoaderRoute: typeof ComposerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/memories/$id': {
      id: '/memories/$id'
      path: '/$id'
      fullPath: '/memories/$id'
      preLoaderRoute: typeof MemoriesIdRouteImport
      parentRoute: typeof MemoriesRoute
    }
    '/composer/dev-modes/$id': {
      id: '/composer/dev-modes/$id'
      path: '/dev-modes/$id'
      fullPath: '/composer/dev-modes/$id'
      preLoaderRoute: typeof ComposerDevModesIdRouteImport
      parentRoute: typeof ComposerRoute
    }
  }
}

interface ComposerRouteChildren {
  ComposerDevModesIdRoute: typeof ComposerDevModesIdRoute
}

const ComposerRouteChildren: ComposerRouteChildren = {
  ComposerDevModesIdRoute: ComposerDevModesIdRoute,
}

const ComposerRouteWithChildren = ComposerRoute._addFileChildren(
  ComposerRouteChildren,
)

interface MemoriesRouteChildren {
  MemoriesIdRoute: typeof MemoriesIdRoute
}

const MemoriesRouteChildren: MemoriesRouteChildren = {
  MemoriesIdRoute: MemoriesIdRoute,
}

const MemoriesRouteWithChildren = MemoriesRoute._addFileChildren(
  MemoriesRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanvasRoute: CanvasRoute,
  ComposerRoute: ComposerRouteWithChildren,
  MemoriesRoute: MemoriesRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
